version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: jwt_auth_postgres
    environment:
      POSTGRES_DB: jwt_auth
      POSTGRES_USER: pos
      POSTGRES_PASSWORD: 1234567
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - jwt_auth_network

volumes:
  postgres_data:

networks:
  jwt_auth_network:
    driver: bridge