spring:
  application:
    name: jwt-auth
  profiles:
    active: dev
  jackson:
    date-format: com.fasterxml.jackson.databind.util.StdDateFormat
    default-property-inclusion: NON_NULL
  thymeleaf:
    cache: false

server:
  port: 8080
  servlet:
    context-path: /

token:
  signing:
    key: "53A73E5F1C4E0A2D3B5F2D784E6A1B423D6F247D1F6E5C3A596D635A75327855"